---
- name: Install python-apt
  command: apt-get -y install python-apt

- name: Install aptitude (some ubuntus dont have it...)
  command: apt-get -y install aptitude

- name: apt-get upgrade 
  action: apt update_cache=yes upgrade=yes

- name: Install essential packages
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - git
  - screen
  - bzip2
  - htop
  - vim
  - locate
  - nload
  - python-pycurl
  - zsh
  - build-essential
  - libssl-dev
  - libdb++-dev
  - libboost-all-dev
  - libqrencode-dev
  - libgmp3-dev
  - git
  - zip
  - automake
  - npm
  - curl
  - unzip
  - autoconf 
  - libminiupnpc-dev
  - miniupnpc   



- name: delte repo to start again
  file: path=/root/navcoin2/  state=absent

- git:
    repo: "{{ navcoin2_git }}"
    version: "{{navcoin2_git_branch}}"
    dest: ~/navcoin2
    clone: yes
    update: yes

- name: curl "http://navcoin.org/files/secp.zip" -o "/root/navcoin2/src/secp256k1/secp.zip"
  shell: curl "http://navcoin.org/files/secp.zip" -o "/root/navcoin2/src/secp256k1/secp.zip"
  ignore_errors: no
  sudo: yes

- name: unzip secp.zip 
  shell: unzip /root/navcoin2/src/secp256k1/secp.zip -d /root/navcoin2/src/secp256k1/
  sudo: yes
  ignore_errors: no


- name: sudo chmod 777 ~/navcoin2/src/secp256k1/* 
  shell: chmod 777 ~/navcoin2/src/secp256k1/*
  sudo: yes
  ignore_errors: no

- name: .~/navcoin2/src/secp256k1//autogen.sh
  shell: ./autogen.sh
          chdir=~/navcoin2/src/secp256k1/
  sudo: yes        
  ignore_errors: no

- name: ./navcoin2/src/secp256k1//configure 
  shell: ./configure --enable-module-recovery
         chdir=~/navcoin2/src/secp256k1/
  sudo: yes
  ignore_errors: no

- name: ~/navcoin2/src/secp256k1/make
  shell: make
         chdir=~/navcoin2/src/secp256k1/
  sudo: yes
  ignore_errors: no

- name: make -f ~/navcoin2/src/makefile.unix -j2
  shell: make -f makefile.unix -j2
         chdir=~/navcoin2/src
  sudo: yes
  ignore_errors: no
# Configure Navcoind
# TODO:

# Download blockchain
# Get blockchain
- name: wget http://www.navcoin.org/files/Nav-Blockchain.zip
  shell: wget http://www.navcoin.org/files/Nav-Blockchain.zip
         chdir=~/navcoin2
  sudo: yes
  ignore_errors: no


- name: unzip Nav-Blockchain.zip
  shell: unzip /root/navcoin2/Nav-Blockchain.zip -d /root/navcoin2/
  sudo: yes
  ignore_errors: no

# Install SubChain
- git:
    repo: clone https://github.com/navcoindev/subchain.git    
    dest: ~/
    clone: yes
    update: yes

- name: mkdir obj
  shell: mkdir obj
          chdir=~/subchain/src
  sudo: yes        
  ignore_errors: no


- name: Make object 777
  file:
    path: /subchain/src/obj
    mode: u=rwX,g=rwX,o=rwX    

- name: make -f makefile.unix -j2
  shell: make -f makefile.unix -j2
         chdir=~/subchain/src
  sudo: yes
  ignore_errors: no
